/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studyapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author youssif
 * date : 4/01/2023
 * Student number : x20252561
 */
public class StudyGUI extends javax.swing.JFrame {
    
    //array list here to store data 
    private ArrayList <Study> study;

    /**
     * Creates new form StudyGUI
     */
    public StudyGUI() {
        study = new ArrayList<>();       //ArrayList 
        initComponents();
        //Jframe Visability mod
        studyTopicLbl.setVisible(true);
        studyTopicTf.setVisible(true);
        teamMatesLbl.setVisible(false);
        teamMatesTf.setVisible(false);
        assesmentNameLbl.setVisible(false);
        assesmentNameTf.setVisible(false);
        
    }
    
    
    public void AutoLoad(){
        //this method here will automatically load and print out the data when running the application, you can alos press on the load button to load the data manually
        File f; 
        FileInputStream inputStream;
        ObjectInputStream oStream;
        try{
            f = new File("studyOutput.dat");            //load file 
            inputStream = new FileInputStream(f);           //establish connection
            oStream = new ObjectInputStream(inputStream);       //data flows through the connection 
            
            study = (ArrayList<Study>) oStream.readObject();          //read obejct in the arrayList
            oStream.close();                                       //terminate the connection
            
        }catch(IOException | ClassNotFoundException e){
            System.out.println(e);
        }
        
        for(Study s : study){
            JOptionPane.showMessageDialog(null, "Automatic Loading : " + "\n"+ s.getDetails());
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeGroup = new javax.swing.ButtonGroup();
        titleLbl = new javax.swing.JLabel();
        dayLbl = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        durationLbl = new javax.swing.JLabel();
        moduleLbl = new javax.swing.JLabel();
        dayTf = new javax.swing.JTextField();
        timeTf = new javax.swing.JTextField();
        durationTf = new javax.swing.JTextField();
        moduleTf = new javax.swing.JTextField();
        groupRB = new javax.swing.JRadioButton();
        personalRB = new javax.swing.JRadioButton();
        typeLbl = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        loadBtn = new javax.swing.JButton();
        studyTopicLbl = new javax.swing.JLabel();
        teamMatesLbl = new javax.swing.JLabel();
        assesmentNameLbl = new javax.swing.JLabel();
        studyTopicTf = new javax.swing.JTextField();
        assesmentNameTf = new javax.swing.JTextField();
        teamMatesTf = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        additionalFunctionalityLbl = new javax.swing.JLabel();
        deleteLastIndexBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        titleLbl.setText("StudyApp");

        dayLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dayLbl.setText("Day : ");

        timeLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        timeLbl.setText("Time :");

        durationLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        durationLbl.setText("Duration in minutes :");

        moduleLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        moduleLbl.setText("Module Name :");

        typeGroup.add(groupRB);
        groupRB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        groupRB.setText("Group Project");
        groupRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupRBActionPerformed(evt);
            }
        });

        typeGroup.add(personalRB);
        personalRB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        personalRB.setText("Personal Sessions");
        personalRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalRBActionPerformed(evt);
            }
        });

        typeLbl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        typeLbl.setText("Select Type : ");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        loadBtn.setText("Load");
        loadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBtnActionPerformed(evt);
            }
        });

        studyTopicLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        studyTopicLbl.setText("Study Topic :");

        teamMatesLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        teamMatesLbl.setText("Team mates :");

        assesmentNameLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        assesmentNameLbl.setText("Assesment name :");

        assesmentNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assesmentNameTfActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        additionalFunctionalityLbl.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        additionalFunctionalityLbl.setText("Additional Functionality : ");

        deleteLastIndexBtn.setText("Delete Last Index");
        deleteLastIndexBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLastIndexBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeLbl)
                    .addComponent(personalRB, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupRB, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deleteBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addBtn)
                                .addGap(35, 35, 35)
                                .addComponent(displayBtn)))
                        .addGap(29, 29, 29)
                        .addComponent(loadBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(durationLbl)
                            .addComponent(moduleLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(moduleTf)
                            .addComponent(studyTopicTf)
                            .addComponent(durationTf, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studyTopicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assesmentNameLbl)
                            .addComponent(teamMatesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teamMatesTf, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assesmentNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(timeLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dayLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dayTf)
                            .addComponent(timeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteLastIndexBtn)
                    .addComponent(additionalFunctionalityLbl))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(personalRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupRB)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayLbl)
                    .addComponent(dayTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLbl)
                    .addComponent(timeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(durationLbl)
                    .addComponent(durationTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moduleLbl)
                    .addComponent(moduleTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studyTopicLbl)
                    .addComponent(studyTopicTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamMatesTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teamMatesLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assesmentNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assesmentNameLbl))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn)
                            .addComponent(displayBtn)
                            .addComponent(loadBtn)
                            .addComponent(deleteLastIndexBtn)))
                    .addComponent(additionalFunctionalityLbl))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn)
                    .addComponent(saveBtn))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personalRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalRBActionPerformed
        // TODO add your handling code here:
        
        studyTopicLbl.setVisible(true);
        studyTopicTf.setVisible(true);
        teamMatesLbl.setVisible(false);
        teamMatesTf.setVisible(false);
        assesmentNameLbl.setVisible(false);
        assesmentNameTf.setVisible(false);
    }//GEN-LAST:event_personalRBActionPerformed

    private void groupRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupRBActionPerformed
        // TODO add your handling code here:
        studyTopicLbl.setVisible(false);
        studyTopicTf.setVisible(false);
        teamMatesLbl.setVisible(true);
        teamMatesTf.setVisible(true);
        assesmentNameLbl.setVisible(true);
        assesmentNameTf.setVisible(true);
    }//GEN-LAST:event_groupRBActionPerformed

    private void assesmentNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assesmentNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assesmentNameTfActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        
        if(personalRB.isSelected()){
            Personal p = new Personal();
            p.setDay(dayTf.getText());
            p.setTime(timeTf.getText()); 
            p.setDuration(Double.parseDouble(durationTf.getText())); 
            p.setModule(moduleTf.getText());
            p.setStudyTopic(studyTopicTf.getText());
            study.add(p);
        }else if(groupRB.isSelected()){
            Group g = new Group();
            g.setDay(dayTf.getText());
            g.setTime(timeTf.getText()); 
            g.setDuration(Double.parseDouble(durationTf.getText())); 
            g.setModule(moduleTf.getText());
            g.setTeamMates(teamMatesTf.getText());
            g.setAssesmentName(assesmentNameTf.getText());
            study.add(g); 
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
    
        if(study.isEmpty()){  
            //print this message if the array is empty
            JOptionPane.showMessageDialog(null, "Sorry the database is empty !");  
        }else{ 
            for(Study s: study){  
                //loop through the content of the array list using a for loop
                JOptionPane.showMessageDialog(null, s.getDetails());
            }//for loop

        }//else
    }//GEN-LAST:event_displayBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        if(study.isEmpty()){
            //print this message if the arrayList is empty
            JOptionPane.showMessageDialog(null, "unable to delete, the data base is empty !"); 
        }else{
            //allow the user to enter the module name to delete the data
            String search = JOptionPane.showInputDialog(null, "Enter the module name for the data you would like to delete");
            for(int i = 0; i < study.size(); i++){
                Study s = study.get(i); //get the index from the arrayList
                
                if(s.getModule().equalsIgnoreCase(search)){
                    study.remove(s);
                    i = i -1; 
                    JOptionPane.showMessageDialog(null, "Data deleted successfully");
                    break;
                }//inner if 
                
            }//for loop
        
        }//else
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        File f; 
        FileOutputStream fStream; 
        ObjectOutputStream oStream;
        
        try{
            f = new File ("studyOutput.dat");         //create the file
            fStream = new FileOutputStream(f);           //prepare to send the file 
            oStream = new ObjectOutputStream(fStream);    //send the file  
            oStream.writeObject(study);                    //write the data in that file 
            oStream.close();                                 //terminate the connection
        
        }catch(IOException e){
            System.out.println(e);           //print out the errors 
        }
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed
        // TODO add your handling code here:
        File f; 
        FileInputStream inputStream;
        ObjectInputStream oStream;
        
        try{
            f = new File("studyOutput.dat");            //load file 
            inputStream = new FileInputStream(f);           //establish connection
            oStream = new ObjectInputStream(inputStream);       //data flows through the connection 
            
            study = (ArrayList<Study>) oStream.readObject();          //read obejct in the arrayList
            oStream.close();                                       //terminate the connection
            
        }catch(IOException | ClassNotFoundException e){
            System.out.println(e);
        }
        
        for(Study s : study){
            JOptionPane.showMessageDialog(null, "Manual Loading :" + "\n"+ s.getDetails());
        }
        
    }//GEN-LAST:event_loadBtnActionPerformed

    private void deleteLastIndexBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLastIndexBtnActionPerformed
        // TODO add your handling code here:
        if(study.isEmpty()){
            //print this message if the arrayList is empty
            JOptionPane.showMessageDialog(null, "unable to delete the last index, the data base is empty"); 
        }else{
            
            for(int i = 0; i < study.size(); i++){
                Study s = study.get(study.size()-1); //select the last index of the array, the most recently added
                study.remove(s);
                JOptionPane.showMessageDialog(null, "Last data entered has been deleted successfully");
                break;  //break the loop to i does not delete twice, error solved
                
            }//for loop
        
        }//else
    }//GEN-LAST:event_deleteLastIndexBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudyGUI().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel additionalFunctionalityLbl;
    private javax.swing.JLabel assesmentNameLbl;
    private javax.swing.JTextField assesmentNameTf;
    private javax.swing.JLabel dayLbl;
    private javax.swing.JTextField dayTf;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteLastIndexBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel durationLbl;
    private javax.swing.JTextField durationTf;
    private javax.swing.JRadioButton groupRB;
    private javax.swing.JButton loadBtn;
    private javax.swing.JLabel moduleLbl;
    private javax.swing.JTextField moduleTf;
    private javax.swing.JRadioButton personalRB;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel studyTopicLbl;
    private javax.swing.JTextField studyTopicTf;
    private javax.swing.JLabel teamMatesLbl;
    private javax.swing.JTextField teamMatesTf;
    private javax.swing.JLabel timeLbl;
    private javax.swing.JTextField timeTf;
    private javax.swing.JLabel titleLbl;
    private javax.swing.ButtonGroup typeGroup;
    private javax.swing.JLabel typeLbl;
    // End of variables declaration//GEN-END:variables
}
