/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package moviesapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author youssif
 * Date: 7/12/2022
 */
public class MoviesGUI extends javax.swing.JFrame {
    
    //declare instance of the connection
    Connection myCon;
    

    /**
     * Creates new form MoviesGUI
     */
    public MoviesGUI() {
        initComponents();
        getConnection();
    }
    
    private void getConnection(){
        //create the connection to the Movies database in mySql
        try {                                                       //ref quide: "jdbc:mysql://localhost:3306/ database name / root / password
            myCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/movies","root","you11");
        }catch(SQLException ex){
            System.out.println("Connection Failed" + ex.getMessage());
        }catch(Exception ex){
            System.out.println(ex);
        }//end of catch
    }//void connection()

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        movieTitleLbl = new javax.swing.JLabel();
        dayLbl = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        movieTitleTf = new javax.swing.JTextField();
        dayTf = new javax.swing.JTextField();
        timeTf = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLbl.setText("MoviesApp");

        movieTitleLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        movieTitleLbl.setText("Movie Title :");

        dayLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dayLbl.setText("Day :");

        timeLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timeLbl.setText("Time :");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movieTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(movieTitleTf, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(dayTf)
                            .addComponent(timeTf))
                        .addGap(138, 138, 138))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addBtn)
                            .addComponent(searchBtn))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayBtn)
                            .addComponent(deleteBtn))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(titleLbl)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieTitleLbl)
                    .addComponent(movieTitleTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayLbl)
                    .addComponent(dayTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLbl)
                    .addComponent(timeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(displayBtn))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn)
                    .addComponent(searchBtn))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        try{
            //create the stament to inject data into sql 
            Statement myStatement = myCon.createStatement();
            
            //inject the data from the user to sql using the stament
            myStatement.executeUpdate("INSERT INTO list_of_movies (Title, movie_day, movie_time)" + "VALUES('" + movieTitleTf.getText() + "','" + dayTf.getText() + "','"  + timeTf.getText() + "')");
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        try{
            Statement myStatement = myCon.createStatement();
            ResultSet myResults = myStatement.executeQuery("SELECT * FROM list_of_movies");
            while(myResults.next()){
                JOptionPane.showMessageDialog(null, "Movie Title : " + myResults.getString("Title") + "\nDay : " + myResults.getString("movie_day") + "\nTime : " + myResults.getString("movie_time"));
            }//while
        
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String search = JOptionPane.showInputDialog(null, "Enter the day of the Movie you would like to search for ");
        try{
            Statement myStatement = myCon.createStatement();
            ResultSet myResults = myStatement.executeQuery("SELECT * FROM list_of_movies");
            
            while(myResults.next()){
                if(myResults.getString("movie_day").equalsIgnoreCase(search)){
                    JOptionPane.showMessageDialog(null,"Movie Title : " + myResults.getString("Title") + "\nDay : " + myResults.getString("movie_day") + "\nTime : " + myResults.getString("movie_time"));
                }//if statment 
            }//while
            
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        String search = JOptionPane.showInputDialog(null, "Enter the Movie title you would like to delete");
        try{
            Statement myStatement = myCon.createStatement();
            ResultSet myResults = myStatement.executeQuery("SELECT * FROM list_of_movies");
            while(myResults.next()){
                if(myResults.getString("Title").equalsIgnoreCase(search)){
                    myStatement.executeUpdate("DELETE FROM list_of_movies WHERE Title ='" + search + "'");
                    JOptionPane.showMessageDialog(null,"Movie Deleted !");
                }
                
            }//while
        
        }catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoviesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoviesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoviesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoviesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoviesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel dayLbl;
    private javax.swing.JTextField dayTf;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel movieTitleLbl;
    private javax.swing.JTextField movieTitleTf;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel timeLbl;
    private javax.swing.JTextField timeTf;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
